### ISSUE TITLE
Blizzard authentification

### ISSUE THREAD

**Issue by void7604** [kamoo1/Kamoo-s-TSM-App#76]
Hello 
I just stumbled on the project ! it's awsome 
I forked the repo and tried to run it on github actions
I added my bnet client ID and secret in my_env 
but i'm getting this error message in the update AH action 
![image](https://github.com/kamoo1/Kamoo-s-TSM-App/assets/85902694/beb88cfb-4b22-481a-a216-912950c2a1ac)

**Comment by kamoo1** [comment]
Blizzard recently banned a bunch cloud provider's IPs out of no reason, most hosting services including Github Actions were affected...

I myself am using a proxy service setup in Cloudflare workers, [here](https://pastebin.com/5n4k4A7V) is a modified version of [Workers-Proxy](https://github.com/aD4wn/Workers-Proxy) that works by mirroring oauth.battle.net site. 

After you've setup the worker, add it to the env var (not secrets) named `BN_OAUTH_URL` and you're good to go.
https://github.com/kamoo1/Kamoo-s-TSM-App/commit/bfc55372105dc691434176588aa9f5ec8c8e5a83
