### ISSUE TITLE
可以顯示區域數據，但找不到伺服器數據

### ISSUE THREAD

**Issue by awafer** [kamoo1/Kamoo-s-TSM-App#83]
現在TSM找不到AuctionDB伺服器數據，估計是TSM改了變量名
程式已同步 1小時 20分鐘
無AuctionDB伺服器數據
AuctionDB 區域數據是 1小時 20分鐘 舊的。

另外，LibRealmInfo的補丁裏，AppHelper.lua的打不上

WARNING:ah.patcher:batch_patch: failed to run job 1/9
WARNING:ah.patcher:batch_patch: failed to run job 2/9
WARNING:ah.patcher:batch_patch: failed to run job 3/9
INFO:ah.patcher:batch_patch: job 4/9 done
WARNING:ah.patcher:batch_patch: failed to run job 5/9
INFO:ah.patcher:batch_patch: job 6/9 done
WARNING:ah.patcher:batch_patch: failed to run job 7/9
WARNING:ah.patcher:batch_patch: failed to run job 8/9
INFO:ah.patcher:batch_patch: job 9/9 done

TSM更新了，裏面的AppHelper.lua也更新了。

**Comment by kamoo1** [comment]
感謝反饋, 剛剛大概看了一下, 的確是TSM把拍賣行數據名改動了, 並且增加了兩項新數據. AppHelper.lua也做了變動. 近期儘量會抽時間修改吧!
